name: 'duplojs action semver'
description: 'Compute semver from pull request titles.'

inputs:
  GITHUB_TOKEN:
    required: true
  GITHUB_REPOSITORY:
    required: true
  GITHUB_BRANCHE:
    required: true

  REGEXP_PATCH:
    required: true
  REGEXP_MINOR:
    required: true
  REGEXP_MAJOR:
    required: true

  PATCH_START_AT: 
    required: false
  MINOR_START_AT:
    required: false
  MAJOR_START_AT:
    required: false
    
  OUTPUT_FORMAT: 
    required: false
  CURRENT_PULL_REQUEST_TITLE: 
    required: false
  PER_PAGE:
    required: false

outputs:
  COMPUTED_VERSION:
    description: 'Computed semver.'

runs:
  using: 'node20'
  main: 'dist/main.js'
